# -*- coding: utf-8 -*-
"""lab 7

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DdTzzqKeyyD4-LskR5YXcSlxir9H8upV
"""

import numpy as np
import scipy
import matplotlib.pyplot as plt
import scipy.signal as signal
from scipy.signal import butter, lfilter
from scipy.io.wavfile import read, write
!python3 -m pip install setuptools --user
!python3 -m pip install cffi --user
!python3 -m pip install sounddevice --user
##!sudo apt-get install libasound-dev
##!pip install sounddevice
import sounddevice
from IPython.display import Audio
import wave
import contextlib

sounddevice.query_devices()

def RecordandPlay(duration):
  fs = 44100
  waveform_rec = sounddevice.rec(fs*duration, channels=1, samplerate=fs, blocking=True)
  waveform_rec + waveform_rec.flatten()
  waveform_rec_times=np.linspace(0,duration-(1/fs), duration*fs)
  numsamples=waveform_rec_times.size
  sounddevice.play(waveform_rec,fs)
  print('done recording')

  print('start playing')
  freq1=440
  freq2=450

  t=np.linspace(0,duration,duration*fs)
  sine_waveform=(0.1)*(np.sin(2*np.pi*freq1*t))
  beat_waveform=(0.1/2)*(np.sin(2*np.pi*freq1*t)+np.sin(2*np.pi*freq2*t))
  Audio(sine_waveform,rate=fs)
  Audio(beat_waveform,rate=fs)

  plt.figure(fidsize=(9,2))
  plt.plot(waveform_rec_times, waveform_rec)
  plt.xlabel('time(s)')
  plt.ylabel('voltage (V)')
  plt.tight_layout()
  plt.show()

def RecordandSave(duration, filename):
  fs=44100
  waveform_rec=sounddevice.rec(fs*duration, channels=1, samplerate=fs, blocking=True)
  waveform_rec=waveform_rec.flatten()
  waveform_rec_times=np.linspace(0,duration-(1/fs),duration*fs)
  numsamples=waveform_rec_times.size
  print ('done recording')

  from scipy.io.wavfile import write
  write(filename,fs,waveform_rec)
  plt.figure(figsize=(9,2))
  plt.plot(waveform_rec_times,waveform_rec)
  plt.xlabel('time(s)')
  plt.ylabel('voltage(V)')
  plt.tightlayout()
  plt.show()

def LoadandPlay(filename):
  fs=44100
  input_wav_fs,input_wave=read(filename)
  return Audio(input_wave,rate=input_wav_fs)

RecordandPlay(5)
